/* eslint-disable */
// This file is auto-generated by TypeScript compiler - do not edit manually
/**
 * Roles as stored on Auth0 tokens for per-tenant permissions.
 * These map directly to the `UserTenantRole` domain entity.
 * TODO(Epic1-Task1.4): confirm role slugs with the Auth0 /rules integration before going live.
 */
export var UserTenantRole;
(function (UserTenantRole) {
    UserTenantRole["ADMIN"] = "tenant:admin";
    UserTenantRole["COORDINATOR"] = "tenant:coordinator";
    UserTenantRole["TEACHER"] = "tenant:teacher";
    UserTenantRole["STAFF"] = "tenant:staff";
    UserTenantRole["PARENT"] = "tenant:parent";
})(UserTenantRole || (UserTenantRole = {}));
/**
 * Org-level roles live alongside tenant roles so we can gate billing,
 * safeguarding exports, and trust-wide features.
 */
export var UserOrgRole;
(function (UserOrgRole) {
    UserOrgRole["ORG_OWNER"] = "org:owner";
    UserOrgRole["ORG_ADMIN"] = "org:admin";
    UserOrgRole["SAFEGUARDING_LEAD"] = "org:safeguarding_lead";
    UserOrgRole["BILLING_MANAGER"] = "org:billing_manager";
    UserOrgRole["SUPPORT"] = "org:support";
})(UserOrgRole || (UserOrgRole = {}));
export const EMPTY_ROLE_SET = { org: [], tenant: [] };
