/* eslint-disable */
// This file is auto-generated by TypeScript compiler - do not edit manually
export const PATHWAY_CONTEXT_PROPERTY = "__pathwayContext";
export const DEBUG_FALLBACK_TOKEN = "debug-staff";
